### ISSUE TITLE
Use an abstraction for `Def` variants.

### ISSUE THREAD

**Issue by 3noch** [ndmitchell/safe#11]
I think many cases of `Def` variants could be covered by a simple `Defaultable` typeclass. I've often wanted this and perhaps `safe` is the best place for it? I'm going off memory, so this may not compile.

```haskell
class Defaultable f where
    defaultTo :: f a -> a -> a

instance Defaultable Maybe where
    defaultTo = flip fromMaybe

instance Defaultable (Either a) where
    defaultTo (Left _) def = def
    defaultTo (Right x) _ = x

takeMay 3 [] `defaultTo` []
-- or, using some infix alias that I am making up: takeMay 3 [] ||> []
```

**Comment by ndmitchell** [comment]
I can see this being useful for some places, but I don't think it's appropriate for the safe library - it seems to be principled in a different direction from how safe is structured (which is fine, and possibly even better, it's just that they probably don't belong in the same package).

It also seems quite verbose, compared to `takeDef`, even if you had an infix version. I also observe both your Defaultable things are Monads, perhaps that's another direction to take this idea? At least MonadFail seems related.

**Comment by 3noch** [comment]
Fair enough. I was mainly interested in your thoughts. I am surprised that something like this is not already present, and I wouldn't be surprised if it is, only by a different (likely more abstract) name. But I still see most code written with explicit calls to `maybe def` and `either def` that I wonder why folks haven't made/utilized more readable forms. In particular, it seems like a nice tool in the context of chaining `Alternatives`: `option1 <|> option2 |> default`.

**Comment by ndmitchell** [comment]
I think everything is some kind of applicative traversal nowadays - I'm sure something like it must be somewhere. Agreed that it should work nicely with alternatives (although I personally rarely use alternatives anyway).
