### ISSUE TITLE
index: Add safe versions of Ix.index

### ISSUE THREAD

**Issue by rbasso** [ndmitchell/safe#21]
[index](http://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Ix.html#v:index) is a partial method from [Ix](http://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Ix.html), defined in package [base](http://hackage.haskell.org/package/base), with the following type:

```haskell
-- | The position of a subscript in the subrange.
index :: Ix a => (a, a) -> a -> Int
```

If the second argument isn't in the range defined by the first argument, it throws an exception:

```
> index ('A', 'C') 'Z'
*** Exception: Ix{Char}.index: Index ('Z') out of range (('A','C'))
```

Would you consider a *pull request* adding the following functions to `Safe.hs`:

```haskell
import Control.Monad (guard)
import Data.Functor  (($>))
import Data.Ix       (Ix, index, inRange)

indexMay :: Ix a => (a, a) -> a -> Maybe Int
indexMay b i = guard (inRange b i) $> index b i

indexDef :: Ix a => Int -> (a, a) -> a -> Int
indexDef def b = fromMaybe def . indexMay b

indexNote :: Ix a => String -> (a, a) -> a -> Int
indexNote note b = fromNote note "indexNote, out of range" . indexMay b
```

**Comment by ndmitchell** [comment]
Sounds good - I would welcome a PR

**Comment by rbasso** [comment]
The implementations are mostly obvious, but I see that you have tests for most of the functions. Should I add tests for those function too?

**Comment by ndmitchell** [comment]
No need for tests - the code is sufficiently straightforward.
