### ISSUE TITLE
maximumBound functions

### ISSUE THREAD

**Issue by minad** [ndmitchell/safe#26]
I think the maximumDef functions are a bit problematic as they are defined now. It would be better if the result value is bounded by the default value instead.

I would like to upstream the following to the safe package. See https://github.com/minad/intro/commit/0aab27f0ad6e62428d73de689f435c7182da4334

Maybe also deprecated the maximumDef functions?

~~~ haskell
-- | The largest element of a foldable structure with respect to the
-- given comparison function. The result is bounded by the value given as the first argument.
maximumBoundBy :: Data.Foldable.Foldable f => a -> (a -> a -> Prelude.Ordering) -> f a -> a
maximumBoundBy x f xs = Data.Foldable.maximumBy f $ x : Data.Foldable.toList xs

-- | The smallest element of a foldable structure with respect to the
-- given comparison function. The result is bounded by the value given as the first argument.
minimumBoundBy :: Data.Foldable.Foldable f => a -> (a -> a -> Prelude.Ordering) -> f a -> a
minimumBoundBy x f xs = Data.Foldable.minimumBy f $ x : Data.Foldable.toList xs

-- | The largest element of a foldable structure with respect to the
-- given comparison function. The result is bounded by 'Prelude.minBound'.
maximumBoundedBy :: (Data.Foldable.Foldable f, Prelude.Bounded a)
                 => (a -> a -> Prelude.Ordering) -> f a -> a
maximumBoundedBy = maximumBoundBy Prelude.minBound

-- | The smallest element of a foldable structure with respect to the
-- given comparison function. The result is bounded by 'Prelude.maxBound'.
minimumBoundedBy :: (Data.Foldable.Foldable f, Prelude.Bounded a)
                 => (a -> a -> Prelude.Ordering) -> f a -> a
minimumBoundedBy = minimumBoundBy Prelude.maxBound

-- | The largest element of a foldable structure.
-- The result is bounded by the value given as the first argument.
maximumBound :: (Data.Foldable.Foldable f, Prelude.Ord a) => a -> f a -> a
maximumBound x xs = Data.Foldable.maximum $ x : Data.Foldable.toList xs

-- | The smallest element of a foldable structure.
-- The result is bounded by the value given as the first argument.
minimumBound :: (Data.Foldable.Foldable f, Prelude.Ord a) => a -> f a -> a
minimumBound x xs = Data.Foldable.minimum $ x : Data.Foldable.toList xs

-- | The largest element of a foldable structure.
-- The result is bounded by 'Prelude.minBound'.
maximumBounded :: (Data.Foldable.Foldable f, Prelude.Ord a, Prelude.Bounded a) => f a -> a
maximumBounded = maximumBound Prelude.minBound

-- | The largest element of a foldable structure.
-- The result is bounded by 'Prelude.maxBound'.
minimumBounded :: (Data.Foldable.Foldable f, Prelude.Ord a, Prelude.Bounded a) => f a -> a
minimumBounded = minimumBound Prelude.maxBound
~~~

**Comment by ndmitchell** [comment]
Doesn't seem unreasonable - probably a better version - but too dangerous to change now. Happy to take a patch.

**Comment by minad** [comment]
Since it is too late to change, I used a different name for them. I will prepare a PR!

**Comment by minad** [comment]
@ndmitchell Could we still deprecate maximumDef etc?

**Comment by ndmitchell** [comment]
@minad sounds sensible.

**Comment by simonmichael** [comment]
FWIW, the quick deprecation has had this effect: my hledger-lib builds started failing, because of -Werror. I think my options are:

- use the new names, and depend on safe >=0.3.18 which is is only a few weeks old, instead of any version of safe. I expect this probably wouldn't cause problems for older GHCs (back to 8.0) or packagers, but I'm not sure.
- use CPP to adjust the code based on the safe version being used
- try to disable deprecation warning in just this module, and think about this again in a year or so

I'll be going with the second I guess.

**Comment by minad** [comment]
I think that is the purpose of deprecations - notify the author of other packages quickly that something is changing. In this case it would be interesting to know if you agree with the change of behavior in general.

While I am not the maintainer of this package, I've seen this issue a few times before and I would honestly like to know how things are supposed to be deprecated gracefully. What do you suggest?
Do you prefer the alternative, to deprecate only with major version bumps, in this case 0.4. Unfortunately then you are stuck until 0.5 with the deprecated functions.

**Comment by simonmichael** [comment]
@minad: I'm afraid I haven't really understood the change well enough to comment; just trying to adapt to it. I'm not sure if there's anything better you could have done, but yes perhaps PVP would say it should cause a bump to 0.4 ? I'm not sure what PVP says about deprecations and adding things.

**Comment by simonmichael** [comment]
In fact I assumed I could just blindly replace the old functions with the correspondingly-named new ones, but that was wrong; the behaviour is different.

When the time comes to remove them, I guess a little migration how-to will be good to have in the changelog/release notes. Even now, it might be worth adding a note pointing out that the new functions are not a direct replacement. 

And in fact, it's not explained here or there what the problem was with the old functions, and why it's worth imposing compatibility hassles on everyone using them ?

Normally in such cases I look for a *-compat package on hackage, which are good for shimming such API changes across GHC versions in a standardish way, but safe isn't covered by those.

**Comment by minad** [comment]
It is explained here in the first sentence:

> I think the maximumDef functions are a bit problematic as they are defined now. It would be better if the result value is bounded by the default value instead.

To explain it a bit better for future reference - if I am passing an empty list, maximumDef returns the default value. But if I pass a non-empty list, the result is the maximum of the list, which can be less than the default value. The maximumBound function behaves monotonically instead. If you look at the Monoid instance for Max (http://hackage.haskell.org/package/base-4.12.0.0/docs/src/Data.Semigroup.html#line-196), it behaves the same as maximumBounded.

**Comment by minad** [comment]
@simonmichael I looked at your hledger repository. There is one use of `maximumDef 0` which should probably be replaced by `maximumBound 0`. If you want to retain the old behavior, you can used `fromMaybe 0 (maximumMay ...)`.

Then there is one use of `maximumDef Nothing` which can also be replaced by maximumMay.

**Comment by simonmichael** [comment]
Thanks for the extra details and hledger hints @minad. Can I ask why the old behaviour was problematic ? 

Again just FWIW, I found the old function easy to understand. maximumDef was undocumented, but the module haddock said "...Def ... takes a default to return on errors". So I understood that maximumDef is maximum, with a default to use for the empty list case. The new maximumBound has a haddock doc (good), but even now I find it really opaque.

**Comment by minad** [comment]
I had bugs due the old behavior, since I expected the function to behave like the `Monoid Max` instance from base and also satisfy `maximumBound a as = maximum (a:as)`. The old function did't satisfy such an equation. If you explicitly write the fold as a recursion you start with the default value and iterate over the list. Then you also obtain the new `maximumBound` function. It is simply more natural, whereas the old `maximumDef` function just makes `maximum` total by arbitrarily defining `maximumDef a [] = a`.
