### ISSUE TITLE
`safe-0.3.21` fails to build with GHC 7.10

### ISSUE THREAD

**Issue by RyanGlScott** [ndmitchell/safe#35]
As seen in [this failing CI job](https://github.com/RyanGlScott/units/actions/runs/7726285760/job/21062269425#step:17:248), `safe-0.3.21` fails to build with GHC 7.10.3:

```
Failed to build safe-0.3.21.
Build log ( /github/home/.cabal/logs/ghc-7.10.3/safe-0.3.21-778d784b35fd9e4ac1f942681fe8cd099de3d419b7f2923fa9feb12f55f4e0b4.log ):
Configuring library for safe-0.3.21..
Preprocessing library for safe-0.3.21..
Building library for safe-0.3.21..

Safe.hs:4:16:
    unknown flag in  {-# OPTIONS_GHC #-} pragma: -Wno-x-partial

Safe.hs:4:16:
    unknown flag in  {-# OPTIONS_GHC #-} pragma: -Wno-unrecognised-warning-flags
Error: cabal-3.10.1.0: Failed to build safe-0.3.21 (which is required by singletons-2.1). See the build log above for details.
```

This is because GHC 7.10 and earlier only support warning flags in the style of `-fwarn-*` and `-fno-warn-*`. The `-W*` and `-Wno-*` style of warning flags weren't introduced until GHC 8.0.

Would you be willing to raise `safe`'s lower version bounds on `base` to `>= 4.9` to exclude it from being buildable with GHC 7.10?

**Comment by ndmitchell** [comment]
Thanks for letting me know. Done on master, and also made a revision on Hackage to the 0.3.21 release.

**Comment by mniip** [comment]
Hi! `safe-0.3.20` also needs a hackage revision for the same reason.
